### ISSUE TITLE
Layout bugs when coming back from suspend

### ISSUE THREAD

**Issue by PenetratingShot** [PapyElGringo/material-shell#24] opened 2019-07-04 19:30 UTC
When you suspend linux and try to log back in, a lot of weird things happen:

**Lock Screen:**
- Icons are large
- stacked horizontally or vertically

**After logging in (on desktop):**
- icons are duplicated
- windows are smaller than they normally are
- there's a small bit of desktop showing above all windows
- everything freezes

This is only fixed with a restart. Also more things might be added to this list the more I play around with it.

**Comment by nununoisy** [comment] 2019-07-04 21:49
I was having this issue too. It went away and I can't reproduce it.

What is your desktop manager? GDM?

**Comment by StanSvec** [comment] 2019-07-05 02:28
Experienced similar behavior. Antergos/GDM/Wayland.

**Comment by PapyElGringo** [comment] 2019-07-05 09:09
Thanks for the feedbacks ! Im currently refactoring the code and that will probably help here !

**Comment by nununoisy** [comment] 2019-07-06 02:37
It happened for me again! Here is a photo I took of my screen (since you can't do a screencap locked) and a screencap after unlocking.
![Locked](https://user-images.githubusercontent.com/9949555/60750367-38c8c480-9f5c-11e9-95a3-c754b7935842.png)
![After unlocking](https://user-images.githubusercontent.com/9949555/60750368-39615b00-9f5c-11e9-8b19-bb9b0b98d4cd.png)

**Comment by PenetratingShot** [comment] 2019-07-06 19:42
Nice to see that it's at least reproduce-able

**Comment by nununoisy** [comment] 2019-07-06 21:22
I've noticed it seems to happen after I suspend my computer (i.e. close the lid) but not when just locking it.

**Comment by PapyElGringo** [comment] 2019-07-06 21:28
With the last version still happen??

**Comment by nununoisy** [comment] 2019-07-06 21:33
I just did a `git pull`. I haven't been able to reproduce it yet, but I will try.

**Comment by nununoisy** [comment] 2019-07-06 21:36
It doesn't seem to be doing it anymore. It should be safe to close the issue but we can always reopen it if necessary.

**Closed** 2019-07-07 18:01 UTC
Labels: bug

**Comment by nununoisy** [comment] 2019-07-08 16:52
After the latest commit it has definitely come back. Now it occurs every time I lock the screen.

**Comment by microstudi** [comment] 2019-07-09 10:54
I have the same issue too. Maybe this should be opened again

**Comment by nununoisy** [comment] 2019-07-09 16:29
After the latest commits it is gone. See if you can reproduce it @microstudi

**Comment by microstudi** [comment] 2019-07-09 20:26
solved indeed! thanks!
